name: goldenerp
description: Golden ERP.
publish_to: "none"

version: 1.0.6+17

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.2
  riverpod: ^2.3.2
  hive: ^2.2.3
  flutter_screenutil: ^5.7.0
  syncfusion_flutter_charts: ^21.2.8
  dio: ^4.0.6
  flutter_easyloading: ^3.0.5
  syncfusion_flutter_datagrid: ^21.1.35
  cached_network_image: ^3.2.3
  cached_memory_image: ^1.3.1
  flutter_bloc: ^8.1.2
  bloc: ^8.1.1
  flutter_barcode_scanner: ^2.0.0
  hive_generator: ^2.0.0
  hive_flutter: ^1.1.0
  build_runner: ^2.3.3
  dropdown_textfield: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
